version: '3'
services:
  backend:
    image: abhi5hek001/booklio-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - booklio_network
    depends_on:
      - redis

  frontend:
    image: abhi5hek001/booklio-frontend:latest
    ports:
      - "5174:80"
    depends_on:
      - backend
    networks:
      - booklio_network

  redis:
    image: redis
    container_name: my-redis
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    networks:
      - booklio_network
    mem_limit: 100m

networks:
  booklio_network:
    driver: bridge
