name: booklio
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: abhi5hek001/app-backend:latest
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001" 
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: abhi5hek001/app-frontend:latest
    env_file:
    - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
