name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push backend
        run: |
          docker build -t abhi5hek001/app-backend:latest ./backend
          docker push abhi5hek001/app-backend:latest

      - name: Build & Push frontend
        run: |
          docker build -t abhi5hek001/app-frontend:latest ./frontend
          docker push abhi5hek001/app-frontend:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 43.204.28.182
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/booklio
            git pull origin main
            docker compose pull
            docker compose up -d --build
